
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztsznzddvhznanmkqusa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0c3puemRkdmh6bmFubWtxdXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTY0OTIsImV4cCI6MjA1OTIzMjQ5Mn0.LYS_6auxePj3vXT5wdqQuouDK46Hy7dIpIegfZMyu5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
